# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d54ba249d528e7f0a67c9f0e65e9f9255aab905b43520b7885e0f2d5804f35f00b56aa2beb2c88fcda172e7ae39b27b9dcc1c3efa60c4f70bb1547e91da19fad

test:
  secret_key_base: 9eb1ca124327a19f599a389844a8cf6e84b2b4cfed50c806f0c2ee5ac82ae89c2d9c49d3485bc0fb9fe9bfe8bb26eec90e1ee50d0ee3ae2873739316ab444e2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
